- .eslintrc.json
- .gitignore
- lib/node/rpc.js
- lib/wallet/account.js
- package-lock.json
- package.json
- test/wallet-test.js
1. Add bslint as a dev dependency
2. Explicitly allow any bracket spacing style (because different ones are used in the upstream code)
3. Fix linting errors introduced in in our fork.
@rsolari For the VSCode ESLint plugin you need to set the path in `hsd/.vscode/settings.json` (which I've gitignored here)
```JSON
{
"eslint.nodePath": "node_modules/bslint",
}
```
> Fix eslint setup

- lib/node/rpc.js
- lib/wallet/rpc.js
- lib/wallet/wallet.js
- package-lock.json
- package.json
This change was necessary to allow our users to have full control over the data stored at their name. Can make PR back to main repo after some user testing, but we need this feature now in to finish the other PR
1. Adds a `sendrawupdate` RPC call to the wallet to set raw hex at a name
2. Adds a `getnamerawresource` RPC call to the wallet AND node to get the raw hex at a name
Note: 99% of this code is copy pasted. I thought it was better to duplicate the `sendupdate`/`getnameresource` code rather than abstract out the commonalities to make future upstream changes easier to merge.
> wallet: add rpc endpoints to deal with raw hex payloads

- lib/dns/key.js
- lib/dns/server.js
- lib/node/fullnode.js
Added configurations to:
- Strip DNSSEC signatures
- Rewrite the start of authority
- Remove a suffix from the zone query
Full-node environment variables:
SOA_REWRITE: string; nameserver domain
SUFFIX: string; host zone
DNSSEC: boolean; strip dnssec signatures
> Add gateway to receive requests with suffix

- lib/wallet/rpc.js
- lib/wallet/wallet.js
Add in-memory idempotency cache to prevent double-sending bids
> Idempotent bids

- lib/wallet/http.js
Usage:
```bash
curl http://x:apikey@localhost:14039/wallet/:wallet/coin-distribution\?bucketExponent\=10
```
Output:
```json
{
"distributions": [
[
{
"minValue": 0,
"maxValue": 100000,
"counts": { "OPEN": 9, "REGISTER": 1, "RENEW": 1 },
"totalValue": 0
},
{
"minValue": 100000,
"maxValue": 1000000,
"counts": { "NONE": 4 },
"totalValue": 3975060
},
{
"minValue": 1000000,
"maxValue": 10000000,
"counts": { "REDEEM": 5, "REGISTER": 2, "NONE": 2 },
"totalValue": 15990580
},
{
"minValue": 10000000,
"maxValue": 100000000,
"counts": {},
"totalValue": 0
},
{
"minValue": 100000000,
"maxValue": 1000000000,
"counts": { "NONE": 1 },
"totalValue": 100000000
},
{
"minValue": 1000000000,
"maxValue": 10000000000,
"counts": { "NONE": 1831 },
"totalValue": 3661854639960
}
]
]
}
```
> wallet: expose a coin distribution endpoint for utxo summary statistics

- lib/primitives/mtx.js
- lib/wallet/wallet.js
Ok, turns out I think this is actually kind of easy once you step back, and I was making it way harder than I needed to.
Turns out there was already a way to sort by value (big to small) in `MTX#CoinSelector`, so I just added a new selector that sorts by reverse value (small to big). It should work with the existing send endpoint. Then, with the `/wallet/:id/coin-distribution` endpoint that @turbomaze already added we can select an appropriate "value" parameter. With `"depth": 1`, we can run the process multiple times in the same block and it won't re-use the new outputs.
If you do a request like:
```
POST http://x:api-key@hsdnode:14039/wallet/hot/send 
{
"outputs":[
{"address":"some-destination-address", "value": ... }
],
selection: 'sweepdust',
depth: 1,
}
```
> 'sweepdust' coin selection

- lib/dns/server.js
These domains were causing problems in the resolver
https://tools.ietf.org/id/draft-chapin-rfc2606bis-00.html#registry
> Blacklist rfc2606 domains from the dns resolver.

- lib/covenants/namestate.js
- lib/primitives/outpoint.js
- lib/wallet/http.js
- lib/wallet/txdb.js
- lib/wallet/wallet.js
Have tested that it works on the receiving end on mainnet with `drugplug/`, a name that I withdrew to a local wallet from namebase. Still need to:
> Add GET /wallet/:id/ownsName/:name

- lib/utils/util.js
- lib/wallet/http.js
- lib/wallet/wallet.js
- package.json
- test/wallet-http-test.js
Batch Finish hsd implementation
> Ridvan batch finish

- lib/wallet/http.js
Saw a noisy error in honeycomb about not being able to parse an error response, this should fix it.
For reference, the error: https://ui.honeycomb.io/namebase/datasets/namebase-web/result/y5thSyxt1K9
> Return an error response hsd-proxy can parse

- lib/wallet/http.js
- lib/wallet/wallet.js
This PR introduces the new sendmany endpoint (previously only present in rpc calls)
It expects the following request format:
```
{
"account": "test",
"passphrase": "",
"subtractfee": false,
"minconf": 2,
"sendto": [
{
"idempotency_key": "a4",
"address": "rs1q8m5g0g325wmxsudhht2uqqp3qx0wha48nkm4da",
"value":5000
},
{
"idempotency_key": "a5",
"address": "rs1qz5nzwhqasgcsght65ajdy8u5syjt7wa76c3wkl",
"value":5000
}
]
}
```
And responds with following format:
```
{
"processedWithdrawals": [
{
"idempotency_key": "a5",
"output_index": 0,
"output": {
"value": 5000,
"address": "hs1qz5nzwhqasgcsght65ajdy8u5syjt7wa7ez0dkd",
"covenant": {
"type": 0,
"action": "NONE",
"items": []
}
}
},
{
"idempotency_key": "a4",
"output_index": 1,
"output": {
"value": 5000,
"address": …
```
> Ridvan sendmany http support

- lib/utils/util.js
- lib/wallet/http.js
- lib/wallet/wallet.js
- package-lock.json
- package.json
- test/utils/util-test.js
- test/wallet-http-test.js
contains batch-reveal wallet code, tested locally, including timeout testing, local tests are failing (9 of them) but it's because our production-namebase have the same tests failing.
> Ridvan batch reveal cache

- test/wallet-test.js
This PR reverts null-open test changes and reduces number of unit tests failing at the moment
Signed-off-by: rozaydin <ridvan@namebase.io>
> revert tests from null open to reduce number of failing test

- lib/wallet/http.js
- lib/wallet/rpc.js
PR removes rawupdate method from hsd.
Signed-off-by: rozaydin <ridvan@namebase.io>
> [WIP] remove update raw from hsd

- lib/wallet/http.js
- lib/wallet/txdb.js
- lib/wallet/wallet.js
Adds a new method to txdb to retrieve pending txes by age, and propagates this information to wallet. This new method used by namebase-plugin.
Reading records from DB does not acquire a lock, for the following reason, when deleting the tx using abandon call, abandon call acquiires a lock and checks if tx is eligible for removal or not.
> Ridvan pending tx by age

- lib/wallet/node.js
- lib/wallet/plugin.js
- lib/wallet/walletdb.js
This makes sure coin cache that takes long to recover, recovers properly before we start responding to the health checks. This is better signal when wallet is back online.
HSD PR: https://github.com/handshake-org/hsd/pull/803
> wallet: preload all wallets before HTTP server is started.

- lib/blockchain/chaindb.js
- lib/wallet/account.js
- lib/wallet/wallet.js
- lib/wallet/walletdb.js
- test/chain-test.js
- test/node-test.js
- test/wallet-filter-test.js
- test/wallet-test.js
The version of https://github.com/namebasehq/hsd/pull/75 w/o patched look ahead.
Use previous behavior and depend on backup/restore logic of the fullnode (manage derivations on import)
Even though this is not Final fix, it's better to have it merged to handle single block gaps.
> wallet: tmp fix for rescan/sync.

- lib/wallet/account.js
anything other than 1k or number <= 231 must not be allowed.
> account: fix max lookahead checks.

- lib/mempool/mempool.js
- lib/protocol/networks.js
- lib/wallet/walletdb.js
- test/mempool-reorg-test.js
- test/mempool-test.js
- test/wallet-auction-test.js
Backport https://github.com/handshake-org/hsd/pull/788 and https://github.com/handshake-org/hsd/pull/671
> Backport mempool updates

- .github/workflows/build.yml
- lib/wallet/http.js
- lib/wallet/rpc.js
- lib/wallet/wallet.js
- test/anyone-can-renew-test.js
- test/dns-test.js
- test/interactive-swap-test.js
- test/mempool-reorg-test.js
- test/wallet-accounts-auction-test.js
- test/wallet-auction-test.js
- test/wallet-deepclean-test.js
- test/wallet-importname-test.js
- test/wallet-rescan-test.js
- test/wallet-test.js
Backport for: https://github.com/handshake-org/hsd/pull/904
>  Add more specific error when linked inputs are pending.
